// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyQ4_fUtDUO8t760uCzkYBk33lyAj32Mc',
    appId: '1:765457884894:web:bb4c1562de0471b6d9044f',
    messagingSenderId: '765457884894',
    projectId: 'nexlock-5f286',
    authDomain: 'nexlock-5f286.firebaseapp.com',
    databaseURL: 'https://nexlock-5f286-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nexlock-5f286.appspot.com',
    measurementId: 'G-B78H09381Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDurHVaiTQf-2Xc1fCZgbU8sQgEI49QYpA',
    appId: '1:765457884894:android:6bc1068eb60f3651d9044f',
    messagingSenderId: '765457884894',
    projectId: 'nexlock-5f286',
    databaseURL: 'https://nexlock-5f286-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nexlock-5f286.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5yQI_KRJ-o8Go3bF4hFbwij5gz9qy4ns',
    appId: '1:765457884894:ios:23b361d97bf208f5d9044f',
    messagingSenderId: '765457884894',
    projectId: 'nexlock-5f286',
    databaseURL: 'https://nexlock-5f286-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nexlock-5f286.appspot.com',
    iosBundleId: 'com.nexlock.nexlock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5yQI_KRJ-o8Go3bF4hFbwij5gz9qy4ns',
    appId: '1:765457884894:ios:23b361d97bf208f5d9044f',
    messagingSenderId: '765457884894',
    projectId: 'nexlock-5f286',
    databaseURL: 'https://nexlock-5f286-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nexlock-5f286.appspot.com',
    iosBundleId: 'com.nexlock.nexlock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyQ4_fUtDUO8t760uCzkYBk33lyAj32Mc',
    appId: '1:765457884894:web:8e33f12e0c41efadd9044f',
    messagingSenderId: '765457884894',
    projectId: 'nexlock-5f286',
    authDomain: 'nexlock-5f286.firebaseapp.com',
    databaseURL: 'https://nexlock-5f286-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nexlock-5f286.appspot.com',
    measurementId: 'G-17V5GQJQED',
  );

}